/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testoct19;

import java.util.ArrayList;

public class Library {

    public static void flattenList(ArrayList<Object> numList, ArrayList<Integer> response) {

        for (Object o : numList) {
            if (o instanceof Integer) {
                Integer num = (Integer) o;
                response.add(num);
            } else if (o instanceof ArrayList) {
                ArrayList<Object> nolist = (ArrayList) o;
                flattenList(nolist, response);
            }
        }
    }
}
