/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testoct19;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {


    @Test
    public void testSuccess() {
        ArrayList<Object> input = new ArrayList<>();

        input.add(1);

        ArrayList<Integer> one = new ArrayList<>();
        one.add(2);
        one.add(3);
        input.add(one);

        ArrayList<Integer> fr = new ArrayList<>();
        fr.add(6);
        fr.add(7);
        ArrayList<Object> th = new ArrayList<>();
        th.add(4);
        th.add(5);
        th.add(fr);

        input.add(th);
        System.out.println("input ->" + input);
        ArrayList<Integer> flatList = new ArrayList<>();
        Library.flattenList(input, flatList);

        System.out.println("flatlist .." + flatList);
    }

    @Test
    public void testSuccess_2() {
        ArrayList<Object> input = new ArrayList<>();

        ArrayList<Integer> one = new ArrayList<>();
        ArrayList<Object> two = new ArrayList<>();
        ArrayList<Object> three = new ArrayList<>();

        one.add(1);
        one.add(2);
        input.add(one);

        ArrayList<Integer> fr = new ArrayList<>();
        fr.add(3);
        fr.add(4);
        ArrayList<Object> th = new ArrayList<>();
        th.add(fr);
        two.add(th);
        input.add(two);

        System.out.println("input ->" + input);
        ArrayList<Integer> flatList = new ArrayList<>();
        Library.flattenList(input, flatList);

        System.out.println("flatlist .." + flatList);
    }
}
